/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExperienceIdIndexImport } from './routes/$experienceId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExperienceIdIndexRoute = ExperienceIdIndexImport.update({
  id: '/$experienceId/',
  path: '/$experienceId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$experienceId/': {
      id: '/$experienceId/'
      path: '/$experienceId'
      fullPath: '/$experienceId'
      preLoaderRoute: typeof ExperienceIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$experienceId': typeof ExperienceIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$experienceId': typeof ExperienceIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$experienceId/': typeof ExperienceIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$experienceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$experienceId'
  id: '__root__' | '/' | '/$experienceId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceIdIndexRoute: typeof ExperienceIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceIdIndexRoute: ExperienceIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$experienceId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$experienceId/": {
      "filePath": "$experienceId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
